package com.example.sammyshuck_cs360activity;


import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {

    private TextView txtGreeting;
    private Button btnSayHello;
    private EditText etxtName;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        txtGreeting = findViewById(R.id.textGreeting);

        btnSayHello = findViewById(R.id.buttonSayHello);
        btnSayHello.setOnClickListener(this::SayHello);
        btnSayHello.setEnabled(false);

        etxtName = findViewById(R.id.nameText);
        etxtName.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                // autogenerated stub
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                btnSayHello.setEnabled(s.toString().trim().length() != 0);
            }

            @Override
            public void afterTextChanged(Editable s) {
                // autogenerated stub
            }
        });
    }

    public void SayHello(View view){
        if (etxtName.getText().toString() != null){
            String greeting = "Hello " + etxtName.getText().toString();
            txtGreeting.setText(greeting);
        } else {
            String err = "You must enter a name";
            txtGreeting.setText(err);
        }
    }
}